title: "Demokratielabore"
description: ""
url: https://demokratielabore.de
markdown: kramdown
exclude:
  - "vendor"
  - "CNAME"
  - "Gemfile*"
  - "mission"
  - "README.md"
  - "*.sh"
  - "doc/"
  - "local/"
  - "update_avatars.py"
  #- "projekte" # uncomment line to speed up jekyll build for development
  #- "blog" # uncomment line to speed up jekyll build for development
  #- "termine" # uncomment line to speed up jekyll build for development
  #- "presse" # uncomment line to speed up jekyll build for development
sass:
    style: :compressed
permalink: /blog/:title
excerpt_separator: "\n"
paginate: 10
paginate_path: "blog/page/:num"
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Collections
collections:
    workshops:
      output: true
      permalink: /workshops/:path/
    angebote:
      output: true
      permalink: /angebot/:path/
    labs:
      output: true
      permalink: /labs/:path/
    publikationen:
      output: true
      permalink: /publikationen/:path/
    ideas:
      output: true
      permalink: /idea/:path/

# page_gen:
#   - data: 'materialsammlung.themen'
#     index_files: true
#     template: 'themen'
#     name: 'title'
#     dir: 'materialsammlung'


staticman:
  branch: "dev"
  server: "https://staticman.okfn.de"
  repository: "okfde/demokratielabore"
